name: potator
description: "A simple Flutter client for the potatoes reverse-fetch proxy"
version: 1.0.0
homepage: https://github.com/neoapps-dev/potator

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: